worker_processes auto;

events {
    worker_connections 1024;
}

rtmp {
    server {
        listen 1935; 
        
        chunk_size 4096;

        application live {
            live on;
            
            record off;
            
            hls on;
            hls_path /tmp/hls;
            hls_fragment 3;
            hls_playlist_length 60;
            
            allow publish ;
            allow publish ;
            deny play all;
        }

        #application secure {
            #live on;

            # Enable stream key authentication
            #on_publish http://localhost/auth;

            #hls on;
            #hls_path /var/www/html/hls;
            #hls_fragment 3;
            #hls_playlist_length 60;
        #}
    }
}

# Keep the HTTP block if you want to serve web content or stream stats later
http { 
    tcp_nopush on;
    directio 512;
    default_type application/octet-stream;

    server {
        listen 8080;
        
        # Optional: Setup a simple page to view RTMP stats
        location /hls {
            # Serve HLS fragments
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            root /tmp;
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *; # Allow cross-origin for players
        }

        location /dash {
            root /var/www/html;
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
        }

        location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
        }
        location /stat.xsl {
            root /var/www/html/rtmp;
        }

        # rtmp control
        location /control {
            rtmp_control all;
        }
    }
}