services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: mysql:8.4
    command: --max_allowed_packet=64M
    container_name: 4331_streaming_DB
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: 4331_streaming_DB
      MYSQL_USER: app
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - 4331_streaming_DB:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  4331_streaming_DB: